(define-module (my sysctl)
  #:use-module (gnu services)
  #:use-module (gnu services sysctl)
  #:export (%sysctl-service))

(define %sysctl-service
  (service sysctl-service-type
   (sysctl-configuration
     (settings (append '(("kernel.sysrq" . "0")
			 ("kernel.unprivileged_userns_clone" . "1")
			 ("kernel.unprivileged_bpf_disabled" . "1")
			 ("kernel.core_uses_pid" . "1")
			 ("dev.tty.ldisc_autoload" . "0")
			 ("kernel.kptr_restrict" . "2")
			 ("net.core.bpf_jit_enable" . "0")
			 ("kernel.ftrace_enabled" . "0")
			 ("net.ipv4.conf.all.log_martians" . "1")
			 ("net.ipv4.conf.all.rp_filter" . "1")
			 ("net.ipv4.conf.default.log_martians" . "1")
			 ("net.ipv4.conf.default.rp_filter" . "1")
			 ("net.ipv4.icmp_echo_ignore_broadcasts" . "1")
			 ("net.ipv4.conf.all.accept_redirects" . "0")
			 ("net.ipv4.conf.all.secure_redirects" . "0")
			 ("net.ipv4.conf.default.accept_redirects" . "0")
			 ("net.ipv4.conf.default.secure_redirects" . "0")
			 ("net.ipv6.conf.all.accept_redirects" . "0")
			 ("net.ipv6.conf.default.accept_redirects" . "0")
			 ("net.ipv4.conf.all.send_redirects" . "0")
			 ("net.ipv4.conf.default.send_redirects" . "0"))
		       %default-sysctl-settings)))))
